[package]
name = "builder-trait"
version = "0.1.0"
edition = "2021"

[features]
default = ["tonic", "prost"]
tonic = ["tonic-build"]
prost = ["prost-build"]

[dependencies]
prost-build = { version = "0.11.1", optional = true }
tempfile = "3.3.0"
tonic-build = { version = "0.8.2", optional = true }

[dev-dependencies]
insta = "1.21.0"
